/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Sitemap_indexDotxmlRouteImport } from './routes/sitemap_index[.xml]'
import { Route as SetupCoworkRouteImport } from './routes/setup-cowork'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.txt]'
import { Route as Post_tagSitemapDotxmlRouteImport } from './routes/post_tag-sitemap[.xml]'
import { Route as PostSitemapDotxmlRouteImport } from './routes/post-sitemap[.xml]'
import { Route as PostSitemappageDotxmlRouteImport } from './routes/post-sitemap$page[.]xml'
import { Route as PageSitemapDotxmlRouteImport } from './routes/page-sitemap[.xml]'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CategorySitemapDotxmlRouteImport } from './routes/category-sitemap[.xml]'
import { Route as AuthorSitemapDotxmlRouteImport } from './routes/author-sitemap[.xml]'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthorSlugRouteImport } from './routes/author.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected'
import { Route as AdminProtectedIndexRouteImport } from './routes/admin/_protected.index'
import { Route as TagSlugPagePageRouteImport } from './routes/tag.$slug.page.$page'
import { Route as CategorySlugPagePageRouteImport } from './routes/category.$slug.page.$page'
import { Route as AuthorSlugPagePageRouteImport } from './routes/author.$slug.page.$page'

const Sitemap_indexDotxmlRoute = Sitemap_indexDotxmlRouteImport.update({
  id: '/sitemap_index.xml',
  path: '/sitemap_index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupCoworkRoute = SetupCoworkRouteImport.update({
  id: '/setup-cowork',
  path: '/setup-cowork',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Post_tagSitemapDotxmlRoute = Post_tagSitemapDotxmlRouteImport.update({
  id: '/post_tag-sitemap.xml',
  path: '/post_tag-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSitemapDotxmlRoute = PostSitemapDotxmlRouteImport.update({
  id: '/post-sitemap.xml',
  path: '/post-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSitemappageDotxmlRoute = PostSitemappageDotxmlRouteImport.update({
  id: '/post-sitemap$page.xml',
  path: '/post-sitemap$page.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSitemapDotxmlRoute = PageSitemapDotxmlRouteImport.update({
  id: '/page-sitemap.xml',
  path: '/page-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySitemapDotxmlRoute = CategorySitemapDotxmlRouteImport.update({
  id: '/category-sitemap.xml',
  path: '/category-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorSitemapDotxmlRoute = AuthorSitemapDotxmlRouteImport.update({
  id: '/author-sitemap.xml',
  path: '/author-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorSlugRoute = AuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedIndexRoute = AdminProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const TagSlugPagePageRoute = TagSlugPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => TagSlugRoute,
} as any)
const CategorySlugPagePageRoute = CategorySlugPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => CategorySlugRoute,
} as any)
const AuthorSlugPagePageRoute = AuthorSlugPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => AuthorSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/author-sitemap.xml': typeof AuthorSitemapDotxmlRoute
  '/category-sitemap.xml': typeof CategorySitemapDotxmlRoute
  '/feed': typeof FeedRoute
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/post-sitemap$page.xml': typeof PostSitemappageDotxmlRoute
  '/post-sitemap.xml': typeof PostSitemapDotxmlRoute
  '/post_tag-sitemap.xml': typeof Post_tagSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/setup-cowork': typeof SetupCoworkRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/author/$slug': typeof AuthorSlugRouteWithChildren
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/tag/$slug': typeof TagSlugRouteWithChildren
  '/admin/': typeof AdminProtectedIndexRoute
  '/author/$slug/page/$page': typeof AuthorSlugPagePageRoute
  '/category/$slug/page/$page': typeof CategorySlugPagePageRoute
  '/tag/$slug/page/$page': typeof TagSlugPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/author-sitemap.xml': typeof AuthorSitemapDotxmlRoute
  '/category-sitemap.xml': typeof CategorySitemapDotxmlRoute
  '/feed': typeof FeedRoute
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/post-sitemap$page.xml': typeof PostSitemappageDotxmlRoute
  '/post-sitemap.xml': typeof PostSitemapDotxmlRoute
  '/post_tag-sitemap.xml': typeof Post_tagSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/setup-cowork': typeof SetupCoworkRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/author/$slug': typeof AuthorSlugRouteWithChildren
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/tag/$slug': typeof TagSlugRouteWithChildren
  '/admin': typeof AdminProtectedIndexRoute
  '/author/$slug/page/$page': typeof AuthorSlugPagePageRoute
  '/category/$slug/page/$page': typeof CategorySlugPagePageRoute
  '/tag/$slug/page/$page': typeof TagSlugPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/author-sitemap.xml': typeof AuthorSitemapDotxmlRoute
  '/category-sitemap.xml': typeof CategorySitemapDotxmlRoute
  '/feed': typeof FeedRoute
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/post-sitemap$page.xml': typeof PostSitemappageDotxmlRoute
  '/post-sitemap.xml': typeof PostSitemapDotxmlRoute
  '/post_tag-sitemap.xml': typeof Post_tagSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/setup-cowork': typeof SetupCoworkRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/author/$slug': typeof AuthorSlugRouteWithChildren
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/tag/$slug': typeof TagSlugRouteWithChildren
  '/admin/_protected/': typeof AdminProtectedIndexRoute
  '/author/$slug/page/$page': typeof AuthorSlugPagePageRoute
  '/category/$slug/page/$page': typeof CategorySlugPagePageRoute
  '/tag/$slug/page/$page': typeof TagSlugPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/author-sitemap.xml'
    | '/category-sitemap.xml'
    | '/feed'
    | '/page-sitemap.xml'
    | '/post-sitemap$page.xml'
    | '/post-sitemap.xml'
    | '/post_tag-sitemap.xml'
    | '/robots.txt'
    | '/search'
    | '/setup-cowork'
    | '/sitemap_index.xml'
    | '/admin'
    | '/admin/login'
    | '/api/contact'
    | '/author/$slug'
    | '/category/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/author/$slug/page/$page'
    | '/category/$slug/page/$page'
    | '/tag/$slug/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/author-sitemap.xml'
    | '/category-sitemap.xml'
    | '/feed'
    | '/page-sitemap.xml'
    | '/post-sitemap$page.xml'
    | '/post-sitemap.xml'
    | '/post_tag-sitemap.xml'
    | '/robots.txt'
    | '/search'
    | '/setup-cowork'
    | '/sitemap_index.xml'
    | '/admin/login'
    | '/api/contact'
    | '/author/$slug'
    | '/category/$slug'
    | '/tag/$slug'
    | '/admin'
    | '/author/$slug/page/$page'
    | '/category/$slug/page/$page'
    | '/tag/$slug/page/$page'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/author-sitemap.xml'
    | '/category-sitemap.xml'
    | '/feed'
    | '/page-sitemap.xml'
    | '/post-sitemap$page.xml'
    | '/post-sitemap.xml'
    | '/post_tag-sitemap.xml'
    | '/robots.txt'
    | '/search'
    | '/setup-cowork'
    | '/sitemap_index.xml'
    | '/admin/_protected'
    | '/admin/login'
    | '/api/contact'
    | '/author/$slug'
    | '/category/$slug'
    | '/tag/$slug'
    | '/admin/_protected/'
    | '/author/$slug/page/$page'
    | '/category/$slug/page/$page'
    | '/tag/$slug/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthorSitemapDotxmlRoute: typeof AuthorSitemapDotxmlRoute
  CategorySitemapDotxmlRoute: typeof CategorySitemapDotxmlRoute
  FeedRoute: typeof FeedRoute
  PageSitemapDotxmlRoute: typeof PageSitemapDotxmlRoute
  PostSitemappageDotxmlRoute: typeof PostSitemappageDotxmlRoute
  PostSitemapDotxmlRoute: typeof PostSitemapDotxmlRoute
  Post_tagSitemapDotxmlRoute: typeof Post_tagSitemapDotxmlRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SetupCoworkRoute: typeof SetupCoworkRoute
  Sitemap_indexDotxmlRoute: typeof Sitemap_indexDotxmlRoute
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiContactRoute: typeof ApiContactRoute
  AuthorSlugRoute: typeof AuthorSlugRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRouteWithChildren
  TagSlugRoute: typeof TagSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap_index.xml': {
      id: '/sitemap_index.xml'
      path: '/sitemap_index.xml'
      fullPath: '/sitemap_index.xml'
      preLoaderRoute: typeof Sitemap_indexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-cowork': {
      id: '/setup-cowork'
      path: '/setup-cowork'
      fullPath: '/setup-cowork'
      preLoaderRoute: typeof SetupCoworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post_tag-sitemap.xml': {
      id: '/post_tag-sitemap.xml'
      path: '/post_tag-sitemap.xml'
      fullPath: '/post_tag-sitemap.xml'
      preLoaderRoute: typeof Post_tagSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-sitemap.xml': {
      id: '/post-sitemap.xml'
      path: '/post-sitemap.xml'
      fullPath: '/post-sitemap.xml'
      preLoaderRoute: typeof PostSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-sitemap$page.xml': {
      id: '/post-sitemap$page.xml'
      path: '/post-sitemap$page.xml'
      fullPath: '/post-sitemap$page.xml'
      preLoaderRoute: typeof PostSitemappageDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-sitemap.xml': {
      id: '/page-sitemap.xml'
      path: '/page-sitemap.xml'
      fullPath: '/page-sitemap.xml'
      preLoaderRoute: typeof PageSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-sitemap.xml': {
      id: '/category-sitemap.xml'
      path: '/category-sitemap.xml'
      fullPath: '/category-sitemap.xml'
      preLoaderRoute: typeof CategorySitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-sitemap.xml': {
      id: '/author-sitemap.xml'
      path: '/author-sitemap.xml'
      fullPath: '/author-sitemap.xml'
      preLoaderRoute: typeof AuthorSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$slug': {
      id: '/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof AuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/tag/$slug/page/$page': {
      id: '/tag/$slug/page/$page'
      path: '/page/$page'
      fullPath: '/tag/$slug/page/$page'
      preLoaderRoute: typeof TagSlugPagePageRouteImport
      parentRoute: typeof TagSlugRoute
    }
    '/category/$slug/page/$page': {
      id: '/category/$slug/page/$page'
      path: '/page/$page'
      fullPath: '/category/$slug/page/$page'
      preLoaderRoute: typeof CategorySlugPagePageRouteImport
      parentRoute: typeof CategorySlugRoute
    }
    '/author/$slug/page/$page': {
      id: '/author/$slug/page/$page'
      path: '/page/$page'
      fullPath: '/author/$slug/page/$page'
      preLoaderRoute: typeof AuthorSlugPagePageRouteImport
      parentRoute: typeof AuthorSlugRoute
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

interface AuthorSlugRouteChildren {
  AuthorSlugPagePageRoute: typeof AuthorSlugPagePageRoute
}

const AuthorSlugRouteChildren: AuthorSlugRouteChildren = {
  AuthorSlugPagePageRoute: AuthorSlugPagePageRoute,
}

const AuthorSlugRouteWithChildren = AuthorSlugRoute._addFileChildren(
  AuthorSlugRouteChildren,
)

interface CategorySlugRouteChildren {
  CategorySlugPagePageRoute: typeof CategorySlugPagePageRoute
}

const CategorySlugRouteChildren: CategorySlugRouteChildren = {
  CategorySlugPagePageRoute: CategorySlugPagePageRoute,
}

const CategorySlugRouteWithChildren = CategorySlugRoute._addFileChildren(
  CategorySlugRouteChildren,
)

interface TagSlugRouteChildren {
  TagSlugPagePageRoute: typeof TagSlugPagePageRoute
}

const TagSlugRouteChildren: TagSlugRouteChildren = {
  TagSlugPagePageRoute: TagSlugPagePageRoute,
}

const TagSlugRouteWithChildren =
  TagSlugRoute._addFileChildren(TagSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthorSitemapDotxmlRoute: AuthorSitemapDotxmlRoute,
  CategorySitemapDotxmlRoute: CategorySitemapDotxmlRoute,
  FeedRoute: FeedRoute,
  PageSitemapDotxmlRoute: PageSitemapDotxmlRoute,
  PostSitemappageDotxmlRoute: PostSitemappageDotxmlRoute,
  PostSitemapDotxmlRoute: PostSitemapDotxmlRoute,
  Post_tagSitemapDotxmlRoute: Post_tagSitemapDotxmlRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SetupCoworkRoute: SetupCoworkRoute,
  Sitemap_indexDotxmlRoute: Sitemap_indexDotxmlRoute,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiContactRoute: ApiContactRoute,
  AuthorSlugRoute: AuthorSlugRouteWithChildren,
  CategorySlugRoute: CategorySlugRouteWithChildren,
  TagSlugRoute: TagSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
