INSERT INTO posts (id, slug, title, status, type, article_type, pillar_slug, pillar_index, author_id, content_html, featured_media_id, created_at, updated_at) VALUES
(112847,'ai-governance-education','AI Governance in Education','draft','post','pillar','ai-governance-education',0,1052,'',NULL,now(),now()),
(112848,'ferpa-ai-compliance-map','FERPA and AI: The Compliance Map','draft','post','pillar','ai-governance-education',1,1052,'',NULL,now(),now()),
(112849,'ai-procurement-standards-universities','AI Procurement Standards for Universities','draft','post','pillar','ai-governance-education',2,1052,'',NULL,now(),now()),
(112850,'student-data-privacy-ai-vendors','Student Data Privacy in the Age of AI Vendors','draft','post','pillar','ai-governance-education',3,1052,'',NULL,now(),now()),
(112851,'academic-integrity-generative-ai','Academic Integrity in the Age of Generative AI','draft','post','pillar','ai-governance-education',4,1052,'',NULL,now(),now()),
(112852,'ai-risk-assessments-higher-ed','AI Risk Assessments for Higher Education','draft','post','pillar','ai-governance-education',5,1052,'',NULL,now(),now()),
(112853,'building-ai-governance-committee','Building an AI Governance Committee','draft','post','pillar','ai-governance-education',6,1052,'',NULL,now(),now()),
(112854,'copyright-training-data-university-liability','Copyright, Training Data, and University Liability','draft','post','pillar','ai-governance-education',7,1052,'',NULL,now(),now()),
(112855,'ai-accessibility-standards-education','AI Accessibility Standards in Education','draft','post','pillar','ai-governance-education',8,1052,'',NULL,now(),now()),
(112856,'ai-ethics-classroom','AI Ethics in the Classroom','draft','post','pillar','ai-governance-education',9,1052,'',NULL,now(),now()),
(112857,'ai-policy-frameworks-universities','The Policy Frameworks Universities Are Adopting','draft','post','pillar','ai-governance-education',10,1052,'',NULL,now(),now()),
(112858,'state-federal-ai-regulation-education','State and Federal AI Regulation Hitting Education','draft','post','pillar','ai-governance-education',11,1052,'',NULL,now(),now()),
(112859,'ai-policy-vs-ai-governance','AI Policy vs AI Governance: The Distinction That Matters','draft','post','pillar','ai-governance-education',12,1052,'',NULL,now(),now()),
(112860,'future-learning-infrastructure','The Future of Learning Infrastructure','draft','post','pillar','future-learning-infrastructure',0,1052,'',NULL,now(),now()),
(112861,'ai-tutors-vs-lms','AI Tutors vs LMS Platforms: The Architecture War','draft','post','pillar','future-learning-infrastructure',1,1052,'',NULL,now(),now()),
(112862,'adaptive-learning-systems','Adaptive Learning Systems: What Actually Works','draft','post','pillar','future-learning-infrastructure',2,1052,'',NULL,now(),now()),
(112863,'agentic-learning-environments','Agentic Learning Environments and the New Classroom','draft','post','pillar','future-learning-infrastructure',3,1052,'',NULL,now(),now()),
(112864,'competency-based-education-ai-era','Competency-Based Education in the AI Era','draft','post','pillar','future-learning-infrastructure',4,1052,'',NULL,now(),now()),
(112865,'ai-classroom-assistants','AI Classroom Assistants: The Quiet Disruption','draft','post','pillar','future-learning-infrastructure',5,1052,'',NULL,now(),now()),
(112866,'assessment-without-tests','Assessment Without Tests: The New Measurement Layer','draft','post','pillar','future-learning-infrastructure',6,1052,'',NULL,now(),now()),
(112867,'digital-credentialing-end-degree','Digital Credentialing and the End of the Degree?','draft','post','pillar','future-learning-infrastructure',7,1052,'',NULL,now(),now()),
(112868,'ai-simulation-learning-professional','AI Simulation Learning: Medicine, Law, Engineering','draft','post','pillar','future-learning-infrastructure',8,1052,'',NULL,now(),now()),
(112869,'autonomous-curriculum-design','Autonomous Curriculum Design','draft','post','pillar','future-learning-infrastructure',9,1052,'',NULL,now(),now()),
(112870,'learning-record-store-data-infrastructure','The Learning Record Store and Education Data Infrastructure','draft','post','pillar','future-learning-infrastructure',10,1052,'',NULL,now(),now()),
(112871,'multimodal-learning-ai','Multimodal Learning AI: Voice, Video, Vision','draft','post','pillar','future-learning-infrastructure',11,1052,'',NULL,now(),now()),
(112872,'personalized-learning-institutional-scale','Personalized Learning at Institutional Scale','draft','post','pillar','future-learning-infrastructure',12,1052,'',NULL,now(),now()),
(112873,'economics-education-ai-era','The Economics of Education in the AI Era','draft','post','pillar','economics-education-ai-era',0,1052,'',NULL,now(),now()),
(112874,'tuition-reset-sticker-price','Tuition Reset: When the Sticker Price Stops Working','draft','post','pillar','economics-education-ai-era',1,1052,'',NULL,now(),now()),
(112875,'ai-cost-reduction-higher-ed-operations','AI-Driven Cost Reduction in Higher Ed Operations','draft','post','pillar','economics-education-ai-era',2,1052,'',NULL,now(),now()),
(112876,'faculty-labor-age-of-ai','Faculty Labor in the Age of AI','draft','post','pillar','economics-education-ai-era',3,1052,'',NULL,now(),now()),
(112877,'administrative-automation-back-office','Administrative Automation: What''s Coming for the Back Office','draft','post','pillar','economics-education-ai-era',4,1052,'',NULL,now(),now()),
(112878,'lifelong-learning-1t-opportunity','The Lifelong Learning Market: The $1T Opportunity Universities Underbuilt','draft','post','pillar','economics-education-ai-era',5,1052,'',NULL,now(),now()),
(112879,'alternative-credentials-economics','Alternative Credentials: The Economics','draft','post','pillar','economics-education-ai-era',6,1052,'',NULL,now(),now()),
(112880,'continuing-education-growth-engine','Continuing Education as Growth Engine','draft','post','pillar','economics-education-ai-era',7,1052,'',NULL,now(),now()),
(112881,'corporate-partnerships-reimagined-higher-ed','Corporate Partnerships Reimagined','draft','post','pillar','economics-education-ai-era',8,1052,'',NULL,now(),now()),
(112882,'degree-to-skill-workforce-alignment','From Degree to Skill: The Workforce Alignment Shift','draft','post','pillar','economics-education-ai-era',9,1052,'',NULL,now(),now()),
(112883,'revenue-diversification-beyond-tuition','Revenue Diversification Beyond Tuition','draft','post','pillar','economics-education-ai-era',10,1052,'',NULL,now(),now()),
(112884,'endowments-donor-strategy-pressure','Endowments, Donor Strategy, and the New Pressure','draft','post','pillar','economics-education-ai-era',11,1052,'',NULL,now(),now()),
(112885,'university-mergers-closures-wave','The Coming Wave of University Mergers and Closures','draft','post','pillar','economics-education-ai-era',12,1052,'',NULL,now(),now());

INSERT INTO post_categories (post_id, category_id)
SELECT id, 27963 FROM posts WHERE id BETWEEN 112847 AND 112885;